twig:
    default_path: '%kernel.project_dir%/templates'

    # Register your global variables under the globals key:
    globals:
        APP_RELEASE: '%env(APP_RELEASE)%'
        
when@test:
    twig:
        strict_variables: true
