# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'en_GB'
    app.locales: en_GB
    app.timezone: 'UTC'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    xVer\MiCartera\Ui\:
        resource: '../src/Ui/'
        exclude:
            - '../src/Ui/DependencyInjection/'
            - '../src/Ui/Entity/'
            - '../src/Ui/Kernel.php'
    xVer\MiCartera\Application\:
        resource: '../src/Application/'
    xVer\MiCartera\Infrastructure\:
        resource: '../src/Infrastructure/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    security_provider.entity_object_repository_loader:
        class: xVer\MiCartera\Application\EntityObjectRepositoryLoader
        factory: ['xVer\MiCartera\Application\EntityObjectRepositoryLoader','doctrine']
        autowire: false
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
    security_provider.account_query:
        class: xVer\MiCartera\Application\Query\Account\AccountQuery
        autowire: false
        arguments:
            - '@security_provider.entity_object_repository_loader'
    xVer\Symfony\Bundle\BaseAppBundle\Ui\Security\Provider:
        arguments:
            - '@security_provider.account_query'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_URL)%'
            - { db_table: 'session' }

when@test:
    services:
        Tests\DataFixtures\:
            resource: '../tests/DataFixtures/'
            arguments:
                - '@Doctrine\Persistence\ManagerRegistry'
            tags: [doctrine.fixture.orm]
